import { SourceNode } from "source-map";
import * as tstl from "typescript-to-lua";

export class TfmCustomPrinter extends tstl.LuaPrinter {
  /* Override printFile */
  protected printFile(file: tstl.File): SourceNode {
    const originalResult = super.printFile(file);
    // Add header comment at the top of the file
    return this.createSourceNode(file, [
      `--[[\n    ${this.relativeSourcePath}\n    Generated by TSTL!\n]]--\n`,
      originalResult,
    ]);
  }
}
